Zee packageRate task
bitNathan/ECE46100-phase-2 pull request #49
Opened 2024-11-18 02:24 UTC by Zinat02

/package/{id}/rate: get: responses: 200: content: application/json: schema: $ref: '#/components/schemas/PackageRating' description: Return the rating. Only use this if each metric was computed successfully. 400: description: There is missing field(s) in the PackageID 403: description: Authentication failed due to invalid or missing AuthenticationToken. 404: description: Package does not exist. 500: description: The package rating system choked on at least one of the metrics. operationId: PackageRate summary: "Get ratings for this package. (BASELINE)" parameters: - name: id schema: $ref: '#/components/schemas/PackageID' in: path required: true - name: X-Authorization description: "" schema: $ref: '#/components/schemas/AuthenticationToken' in: header required:

2024-11-18 16:59 UTC, bitNathan requested changes
I think all the other files we've made for endpoints have been in backend/src instead of root/src, if you could move all these around a bit that'd help everything stay more organized

connection.ts and packageRate should be in backend/src/routes specifically I'd think

I also don't think we should be expecting any authentication tokens since we're not going down that project track.

Testing content looks good though, and that'll be really helpful as a framework for other endpoints. Just the location is all I'd want to change so it's in backend

2024-11-20 23:50 UTC, Zinat02 commented
done

2024-11-25 01:42 UTC, MadSons reviewed
Make sure to test the implementation manually thorugh running both the backend and frontend and then attempting to get the rating of a URL or package. Also ensure error codes are all handled properly as the OpenAPI spec sheet states.

2024-11-25 01:42 UTC, MadSons commented on package.json
We shouldn't have any package.json files in our root directory, we have it structured so that there is one in both the frontend and backend potions since dependencies are different.

2024-11-25 01:42 UTC, MadSons commented on backend/src/routes/packageRate.ts
This should be in a similar format as the file package.ts.

it should be a call to router.get('/package/:id/rate', async (req, res) => {

See my current progress on router.ts [here](https://github.com/bitNathan/ECE46100-phase-2/blob/19-download-packages/backend/src/routes/package.ts)

2024-11-25 01:42 UTC, MadSons commented on backend/src/routes/connection.ts
Not sure if we want to use dotenv. I think those environment variables should be manually set.

Also, see package.ts [here[(https://github.com/bitNathan/ECE46100-phase-2/blob/19-download-packages/backend/src/routes/package.ts) to view how I connect to the database and what is stored.

2024-11-25 01:45 UTC, MadSons requested changes
Make sure to pull main into your branch before attempting to merge into main.

2024-11-26 04:46 UTC, Zinat02 commented
i made all the changes that were requested, please check and make sure everything is right or if i need to do any other tweaks.

2024-11-29 17:10 UTC, bitNathan commented
closed because of new updated PR

2024-11-29 17:10 UTC, closed without merging